#author#======================================
#file:LIBRARY.py
#wangxiaochen CFR7445 2022.01.14
#Copyright (c) 2022 一天两根冰棍
#=============================================

#key value define#============================
#可用机场库------
airport_inuse = ("ZBAA",
                 "ZBAD",
                 "ZBDS",
                 "ZBHH",
                 "ZBLA",
                 "ZBMZ",
                 "ZBSJ",
                 "ZBTJ",
                 "ZBYN",
                 "ZGDY",
                 "ZGGG",
                 "ZGHA",
                 "ZGKL",
                 "ZGNN",
                 "ZGOW",
                 "ZGSZ",
                 "ZHCC",
                 "ZHHH",
                 "ZJHK",
                 "ZJQH",
                 "ZJSY",
                 "ZLDH",
                 "ZLIC",
                 "ZLLL",
                 "ZLXN",
                 "ZLXY",
                 "ZPJH",
                 "ZPLJ",
                 "ZPMS",
                 "ZPPP",
                 "ZSAM",
                 "ZSCG",
                 "ZSCN",
                 "ZSFZ",
                 "ZSHC",
                 "ZSJN",
                 "ZSNB",
                 "ZSNJ",
                 "ZSNT",
                 "ZSOF",
                 "ZSPD",
                 "ZSQD",
                 "ZSQZ",
                 "ZSSH",
                 "ZSSS",
                 "ZSTX",
                 "ZSWH",
                 "ZSWX",
                 "ZSWZ",
                 "ZSXZ",
                 "ZSYA",
                 "ZSYN",
                 "ZSYT",
                 "ZSYW",
                 "ZSZS",
                 "ZUCK",
                 "ZUGY",
                 "ZULS",
                 "ZUTF",
                 "ZUUU",
                 "ZUXC",
                 "ZWSH",
                 "ZWTN",
                 "ZWWW",
                 "ZYCC",
                 "ZYHB",
                 "ZYJM",
                 "ZYMD",
                 "ZYQQ",
                 "ZYTL",
                 "ZYTX",
                 "ZYYJ"
                 ) #机场四字码
airport_inuse_chinese = ("北京首都国际机场",
                         "北京大兴国际机场",
                         "鄂尔多斯伊金霍洛国际机场",
                         "呼和浩特白塔国际机场", 
                         "呼伦贝尔海拉尔国际机场", 
                         "满洲里西郊国际机场",
                         "石家庄正定国际机场",
                         "天津滨海国际机场",
                         "太原武宿国际机场",
                         "张家界荷花国际机场",
                         "广州白云国际机场",
                         "长沙黄花国际机场",
                         "桂林两江国际机场",
                         "南宁吴圩国际机场",
                         "揭阳潮汕国际机场",
                         "深圳宝安国际机场",
                         "郑州新郑国际机场",
                         "武汉天河国际机场",
                         "海口美兰国际机场",
                         "琼海博鳌国际机场",
                         "三亚凤凰国际机场",
                         "敦煌莫高国际机场",
                         "银川河东国际机场",
                         "兰州中川国际机场",
                         "西宁曹家堡国际机场",
                         "西安咸阳国际机场",
                         "西双版纳嘎洒国际机场",
                         "丽江三义国际机场",
                         "德宏芒市国际机场",
                         "昆明长水国际机场",
                         "厦门高崎国际机场",
                         "常州奔牛国际机场",
                         "南昌昌北国际机场",
                         "福州长乐国际机场",
                         "杭州萧山国际机场",
                         "济南遥墙国际机场",
                         "宁波栎社国际机场",
                         "南京禄口国际机场",
                         "南通兴东国际机场",
                         "合肥新桥国际机场",
                         "上海浦东国际机场",
                         "青岛胶东国际机场",
                         "泉州晋江国际机场",
                         "淮安涟水国际机场",
                         "上海虹桥国际机场",
                         "黄山屯溪国际机场",
                         "威海大水泊国际机场",
                         "苏南硕放机场",
                         "温州龙湾国际机场",
                         "徐州观音国际机场",
                         "扬州泰州国际机场",
                         "盐城南洋国际机场",
                         "烟台蓬莱国际机场",
                         "义务机场",
                         "舟山普陀山国际机场",
                         "重庆江北国际机场",
                         "贵阳龙洞堡国际机场",
                         "拉萨贡嘎国际机场",
                         "成都天府国际机场",
                         "成都双流国际机场",
                         "西昌青山国际机场",
                         "喀什机场",
                         "和田机场",
                         "乌鲁木齐地窝堡国际机场",
                         "长春龙嘉国际机场",
                         "哈尔滨太平国际机场",
                         "佳木斯机场",
                         "牡丹江海浪国际机场",
                         "齐齐哈尔三家子国际机场",
                         "大连周水子国际机场",
                         "沈阳桃仙国际机场",
                         "延吉朝阳川国际机场",
                         ) #机场中文名
airport_inuse_english = (" Beijing Capital International Airport ",
                         " Beijing Daxing International Airport ",
                        " Ordos Ijin Horo International Airport ",
                        " Hohhot White Tower International Airport ",
                        " Hulunbuir Hailar International Airport ",
                        " Manzhouli West Suburban International Airport ",
                        " Shijiazhuang Zhengding International Airport ",
                        " Tianjin Binhai International Airport ",
                        " Taiyuan Wushu International Airport ",
                        " Zhangjiajie Lotus International Airport " ,
                        " Guangzhou Baiyun International Airport " ,
                        " Changsha Huanghua International Airport " ,
                        " Guilin Liangjiang International Airport ",
                        " Nanning Wuwei International Airport ",
                        " Jieyang Chaoshan International Airport ",
                        " Shenzhen Bao 'an International Airport ",
                        " Zhengzhou Xinzheng International Airport ",
                        " Wuhan Tianhe International Airport ",
                        " Haikou Meilan International Airport ",
                        " Qionghai Boao International Airport ",
                        " Sanya Phoenix International Airport ",
                        " Dunhuang Mogao International Airport ",
                        " Yinchuan Hedong International Airport ",
                        " Lanzhou Zhongchuan International Airport ",
                        " Xining Caojiapu International Airport ",
                        " Xi 'an Xianyang International Airport ",
                        " Xishuangbanna Gasa International Airport ",
                        " Lijiang Sanyi International Airport ",
                        " Dehong Mangshi International Airport ",
                        " Kunming Changshui International Airport ",
                        " Xiamen Gaoqi International Airport ",
                        " Changzhou Benniu International Airport ",
                        " Nanchang Changbei International Airport ",
                        " Fuzhou Changle International Airport ",
                        " Hangzhou Xiaoshan International Airport ",
                        " Jinan Yaoqiang International Airport ",
                        " Ningbo Lishe International Airport ",
                        " Nanjing Lukou International Airport ",
                        " Nantong Xingdong International Airport ",
                        " Hefei Xinqiao International Airport ",
                        " Shanghai Pudong International Airport ",
                        " Qingdao Jiaodong International Airport ",
                        " Quanzhou Jinjiang International Airport ",
                        " Huai 'an Lianshui International Airport ",
                        " Shanghai Hongqiao International Airport ",
                        " Huangshan Tunxi International Airport ",
                        " Weihai Dashuipu International Airport ",
                        " Sunan Shuofang International Airport ",
                        " Wenzhou Longwan International Airport ",
                        " Xuzhou Guanyin International Airport ",
                        " Yangzhou Taizhou International Airport ",
                        " Yancheng Nanyang International Airport ",
                        " Yantai Penglai International Airport ",
                        " Voluntary airport ",
                        " Zhoushan Putuo International Airport ",
                        " Chongqing Jiangbei International Airport ",
                        " Guiyang Longdongpu International Airport ",
                        " Lhasa Gongga International Airport ",
                        " Chengdu Tianfu International Airport ",
                        " Chengdu Shuangliu International Airport ",
                        " Xichang Qingshan International Airport ",
                        " Kashgar Airport ",
                        " Hotan Airport ",
                        " Urumqi Diwopu International Airport ",
                        " Changchun Longjia International Airport ",
                        " Harbin Taiping International Airport ",
                        " Jiamusi Airport ",
                        " Mudanjiang Wave International Airport ",
                        " Qiqihar Sanjiazi Airport ",
                        " Dalian Zhoushuizi International Airport ",
                        " Shenyang Taoxian International Airport ",
                        " Yanji Chaoyang Chuan International Airport ") #机场英文名
#可用通播代码库------
information_code_inuse = ("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", \
    "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z") #通播代码字母
information_code_inuse_word = ("alpha ", "bravo ", "charlie ", "delta ", "echo ", "foxtrot ", "golf ", "hotel ", \
     "india ", "juliet ", "kilo ", "lima ", "mike ", "november ", "oscar ", "papa ", "quebec ", "romeo ", "sierra ", \
     "tango ", "uniform ", "victor ", "whiskey ", "Xray ", "Yankee ", "Zulu ") #通播代码读音
#可用数字库------
number_inuse_chinese = ("洞", "妖", "两", "三", "四", "五", "六", "拐", "八", "九") #数字中文读音
number_inuse_english = ("zero ", "one ", "too ", "tree ", "four ", "five ", "six ", "seven ", "eight ", "nine ") #数字英文读音
#可用时间库（UTC）------
UTC_time_inuse = ("0000", "0100", "0200", "0300", "0400", "0500", "0600", "0700", "0800", "0900", \
    "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "1900", "2000", \
    "2100", "2200", "2300")
#可用跑到模式库------
runway_mode_inuse_chinese = ("不指定(单跑道)", \
                             "独立平行进近，独立平行离场", \
                             "相关平行进近，独立平行离场", \
                             "隔离平行运行")
runway_mode_inuse_english = ("不指定(单跑道)", \
                             " independent parallel approaches，independent parallel departures ", \
                             " Correlated parallel approach，independent parallel departures ", \
                             " segregated parallel operation ")
#可用气象库------
meteorological_inuse = () #气象缩写代码
meteorological_inuse_chinese = () #气象中文解释
meteorological_inuse_english = () #气象英文解释
#=============================================
